theme: jekyll-theme-hacker
title: markgreene74's pages
subtitle: About me and my professional development
description: About me and my professional development. A technical space where I talk about Python, Data Science and Machine learning.
